package okcoin

const (
	OKCOIN_TIME_URI = "/api/general/v3/time"

	ACCOUNT_CURRENCIES                  = "/api/account/v3/currencies"
	ACCOUNT_DEPOSIT_ADDRESS             = "/api/account/v3/deposit/address"
	ACCOUNT_DEPOSIT_HISTORY             = "/api/account/v3/deposit/history"
	ACCOUNT_DEPOSIT_HISTORY_CURRENCY    = "/api/account/v3/deposit/history/{currency}"
	ACCOUNT_LEDGER                      = "/api/account/v3/ledger"
	ACCOUNT_WALLET                      = "/api/account/v3/wallet"
	ACCOUNT_WALLET_CURRENCY             = "/api/account/v3/wallet/{currency}"
	ACCOUNT_WITHDRAWAL                  = "/api/account/v3/withdrawal"
	ACCOUNT_WITHDRAWAL_FEE              = "/api/account/v3/withdrawal/fee"
	ACCOUNT_WITHDRAWAL_HISTORY          = "/api/account/v3/withdrawal/history"
	ACCOUNT_WITHDRAWAL_HISTORY_CURRENCY = "/api/account/v3/withdrawal/history/{currency}"
	ACCOUNT_TRANSFER                    = "/api/account/v3/transfer"
	ACCOUNT_ASSET_VALUATION             = "/api/account/v3/asset-valuation"
	ACCOUNT_FIAT_WITHDRAWAL             = "/api/account/v3/jpywithdrawal"
	ACCOUNT_FIAT_WITHDRAWAL_HISTORY     = "/api/account/v3/jpyWithdrawal/history"
	ACCOUNT_FIAT_DEPOSIT_HISTORY        = "/api/account/v3/jpyDeposit/history"

	SPOT_ACCOUNTS                 = "/api/spot/v3/accounts"
	SPOT_ACCOUNTS_CURRENCY        = "/api/spot/v3/accounts/{currency}"
	SPOT_ACCOUNTS_CURRENCY_LEDGER = "/api/spot/v3/accounts/{currency}/ledger"
	SPOT_ORDERS                   = "/api/spot/v3/orders"
	SPOT_BATCH_ORDERS             = "/api/spot/v3/batch_orders"
	SPOT_CANCEL_ORDERS_BY_ID      = "/api/spot/v3/cancel_orders/{order_client_id}"
	SPOT_CANCEL_BATCH_ORDERS      = "/api/spot/v3/cancel_batch_orders"
	SPOT_ORDERS_PENDING           = "/api/spot/v3/orders_pending"
	SPOT_ORDERS_BY_ID             = "/api/spot/v3/orders/{order_client_id}"
	SPOT_FILLS                    = "/api/spot/v3/fills"
	SPOT_ORDER_ALGO               = "/api/spot/v3/order_algo"
	SPOT_CANCEL_ALGOS             = "/api/spot/v3/cancel_batch_algos"
	SPOT_GET_ORDER_ALGOS          = "/api/spot/v3/algo"
	SPOT_TRADE_FEE                = "/api/spot/v3/trade_fee"
	SPOT_TRADE_FEE_ALL            = "/api/spot/v3/trade_fee_all"
	SPOT_INSTRUMENTS              = "/api/spot/v3/instruments"
	SPOT_TRADE_FEE_BY_INSTRUMENTID= "/api/spot/v3/trade_fee/{instrument_id}"
	SPOT_INSTRUMENT_BOOK          = "/api/spot/v3/instruments/{instrument_id}/book"
	SPOT_INSTRUMENTS_TICKER       = "/api/spot/v3/instruments/ticker"
	SPOT_INSTRUMENT_TICKER        = "/api/spot/v3/instruments/{instrument_id}/ticker"
	SPOT_INSTRUMENT_TRADES        = "/api/spot/v3/instruments/{instrument_id}/trades"
	SPOT_INSTRUMENT_CANDLES       = "/api/spot/v3/instruments/{instrument_id}/candles"
)
